name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - 2.4
          - 2.5
          - 2.6
        
        include:
          - os: 'ubuntu'
            ruby: '2.6'
            env: COVERAGE=PartialSummary,Coveralls
    
    runs-on: ${{matrix.os}}-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{runner.os}}-gem-${{hashFiles('**/Gemfile.lock')}}
        restore-keys: |
          ${{runner.os}}-gem-
    - name: Package install
      run: |
        sudo apt-get install pkg-config
        gem install bundler:2.0.2
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: ${{matrix.env}} bundle exec rspec
